version: "3.6"
services:
  hits:
    build: .
    ports:
      - "5000:5000"
    networks:
      - my-network
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
     
